# .github/dependabot.yml
version: 2
updates:
  # Automatically update GitHub Actions
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    assignees:
      - kotaoue

  # Automatically update npm packages
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    assignees:
      - kotaoue
